landscaper integration
gardener/gardener-extension-os-gardenlinux pull request #31
Opened 2021-05-11 09:29 UTC by jschicktanz

**How to categorize this PR?**

/area TODO
/kind enhancement
/os garden-linux

**What this PR does / why we need it**:
adds artifacts for Landscaper integration (blueprint, resources definition file, component descriptor build script)

co-authored by @enrico-kaack-comp 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature operator
- adds artifacts for Landscaper integration
```

2021-05-21 06:02 UTC, rfranzke commented
/assign @schrodit

2021-05-21 06:21 UTC, schrodit requested changes

2021-05-21 06:21 UTC, schrodit commented on .landscaper/blueprint/deploy-executions.yaml
> +    apiVersion: manifest.deployer.landscaper.gardener.cloud/v1alpha1
you should use `v1alpha2`
```suggestion
    apiVersion: manifest.deployer.landscaper.gardener.cloud/v1alpha2
```

2021-05-21 06:21 UTC, schrodit commented on .landscaper/component-descriptor.yaml
> +# the base component descriptor will be provided by the pipeline and modified by the .ci/component_descriptor script
why do you need this file?
In the ci pipeline the base component descriptor from the gardener-ci is used

2021-05-21 06:21 UTC, schrodit commented on .landscaper/resources.yaml
> +  path: "../charts/gardener-extension-os-gardenlinux"
don't you also need the preserveDir for helm charts?

2021-05-25 09:52 UTC, schrodit requested changes

2021-05-25 09:52 UTC, schrodit commented on .landscaper/blueprint/deploy-executions.yaml
> +      - apiVersion: core.gardener.cloud/v1beta1
the v1alpha2 has a different struct: 
```suggestion
    manifests:
      - policy: manage
         manifest: apiVersion: core.gardener.cloud/v1beta1
```

2021-06-11 06:31 UTC, rfranzke commented
/ping @schrodit

2021-06-11 07:54 UTC, schrodit requested changes
just a minor change of the media type. otherwise lgtm

2021-06-11 07:54 UTC, schrodit commented on .landscaper/resources.yaml
> +    mediaType: "application/vnd.gardener.landscaper.blueprint.v1+tar+gzip"
```suggestion
    mediaType: "application/vnd.gardener.landscaper.blueprint.layer.v1.tar+gzip"
```
update to the newer oci spec compliant media types

2021-06-11 08:20 UTC, schrodit approved these changes

2021-06-11 12:53 UTC, rfranzke approved these changes

2021-06-11 13:02 UTC, merged